[tools]
go = "1.25.5"
task = "3.45.5"
golangci-lint = "2.7.2"
"npm:markdownlint-cli2" = "0.20.0"
actionlint = "1.7.9"
goreleaser = "2.13.0"

[env]
GO111MODULE = "on"
GOFLAGS = "-mod=readonly"
CGO_ENABLED = "0"
