[tools]
go = "1.26.0"
task = "3.45.5"
golangci-lint = "2.9.0"
actionlint = "1.7.10"
goreleaser = "2.13.0"
jsonschema = "12.10.1"
markdownlint-cli2 = "0.21.0"

[env]
GO111MODULE = "on"
GOFLAGS = "-mod=readonly"
CGO_ENABLED = "0"
